[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-cors = "0.7.0"
serde = { version = "1.0", features = ["derive"]}
serde_json = "1.0.133"
sqlx = { version = "0.8.2", features = ["mysql", "runtime-async-std"] }
dotenv = "0.15"
bcrypt = "0.16.0"